### PR TITLE
Multiple action icons

### PR DESCRIPTION
**Pull request by amyerz**
* update icon props actions to array, allow multiple actions

### CODE REVIEW

**Comment by sks** [comment]
LGTM: Thanks @amyerz

**Comment by jimdefrisco** [comment]
@amyerz @sks For future reference - this change meant a change to the API (the icons.action property changed from a string to an array of strings), so more than just the minor version number should have been changed. (This caused a failure in our recent push to production).

**Comment by gstroup** [comment]
Also, I think we should try to make API changes backwards compatible whenever possible.  (i.e. accept either string or array in this case.)

**Comment by sks** [comment]
thanks for bringing this to the attention.

I thought @amyerz already took care of the polymer 1 use case in https://github.com/predixdesignsystem/px-accordion/pull/14

**Comment by sks** [comment]
Wish there was a way to create [github pull request template](https://github.com/stevemao/github-issue-templates) at org level. the [feature](https://github.community/t5/How-to-use-Git-and-GitHub/Pull-Request-Template-per-Organization/td-p/6281) request has been put in place.

The template should cover these things for sure

- [ ]  Update bower.json
- [ ] Update package.json
- [ ] Run gulp to update the api doc

**Comment by amyerz** [comment]
Added issue and will update to accept string per @gstroup suggested.
https://github.com/predixdesignsystem/px-accordion/issues/15

**Pull request merged**
